detector:
  lx: 4320
  ly: 4320
  lz: 4320
  gap_x: 5
  spacing_y: 500
  spacing_z: 500
  cathode_gap: 8
  refractive_index: 1.2373
  PMT:
    radius: 50
    total_eff: 0.2
    pmt_pepc: general
    pmt_ang_eff: general
    pmt_tts: general
    t_threshold: 0.05
    charge_range: 10
    charge_resolution: 100
    time_min: -5
    time_max: 15
    time_resolution: 100

photon:
  sample: True
  n_photon: 30000
  n_photon_pos: 50000
  resolution: 100

io:
  loader:
    input_file: /sdf/home/j/junjie/sdf-data/FM/playground/first_trial/first_trial_4320x4320x4320_10000000_8.h5
  writer:
    output_dir: /sdf/home/j/junjie/sdf-data/FM/playground/first_trial
    output_prefix: first_trial